---
- name: Install vector
  hosts: vector-01
  tasks:
    - block:
        - name: Get vector distrib
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/{{vector_version}}/{{ item }}-{{ vector_version }}-1.x86_64.rpm"
            dest: "./{{ item }}-{{ vector_version }}.rpm"
          with_items: "{{ vector_packages }}"
          # https://packages.timber.io/vector/0.22.3/vector-0.22.3-1.x86_64.rpm
    - name: Install vector package
      become: true
      ansible.builtin.yum:
        name:
          - vector-{{ vector_version }}.rpm
      notify: Start vector service
